[project]
name = "ebay-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sheshmltv", email = "sheshanth@techvariable.com" }
]
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.2.3",
    "httpx>=0.27.0",
    "temporalio>=1.18.0",
]

[project.scripts]
ebay-worker = "ebay_client.worker:run_worker"
ebay-run = "ebay_client.run:run_pipeline"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
